modLoader="javafml"
loaderVersion="[38,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/AceCraft/issues"
[[mods]]
modId="acecraft"
version="4.0"
displayName="AceCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/acecraft"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Lorem Ipsum
'''
[[dependencies.acecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.acecraft]]
    modId="lucky77"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"