modLoader="javafml"
loaderVersion="[32,)" #mandatory (26 is current forge version)
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/AceCraft/issues"
[[mods]]
modId="acecraft"
version="v09"
displayName="AceCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/acecraft"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Lorem Ipsum
'''
[[dependencies.acecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"